### PR TITLE
DatabaseConnection class - prepareted statement Raphaël

### PR DESCRIPTION
**Pull request by RaphaelDG**
Secure class with prepared statement.

### CODE REVIEW

**Review by powerfulsheron — DISMISSED** [review]
- keep the name DataBaseConnect
- where are the getters and setters for server, database, uid, password, and connectionString ????
- are you sure you can use a message box in a class ?

**Comment by RaphaelDG** [comment]
Changes done.

**Review by powerfulsheron — DISMISSED** [review]
Seems like you don't get it, you need a getter and a setter for every variable in your class.

**Comment by RaphaelDG** [comment]
You can commit your changes on my branch if you want. We're waiting for your class to take some examples.

I disprove the fact to have 4 geters for databaseConnection string, this is clearly junk code. 
The string returned by the Getter is perfectly understandable.

If you read the code, you will see that there is a Setter method for all variables.

**Comment by powerfulsheron** [comment]
junk code ? don't be rude please. It's a common practice

Indeed the string returned by the connection string getter is understandable, 
but what if you want to set or to get only the uid ?? 

I'll show you what i did tonight, I have work to do right now

**Pull request merged**
